version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: vault_track_mongo
    ports:
      - '37017:27017'
    environment:
      - MONGO_INITDB_DATABASE=vault-track
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
